require:
  - standard/cop/block_single_line_braces
  - rubocop-md

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'benchmarks/**/*'
    - '**/node_modules/**/*'
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: disable
  TargetRubyVersion: 3.1

inherit_gem:
  standard: config/base.yml

Standard/BlockSingleLineBraces:
  Enabled: false

Layout/InitialIndentation:
  Enabled: false

# Code blocks nested in Markdown lists are indented, which trips indentation cops.
Layout/IndentationConsistency:
  Enabled: false
