ignore:
 - "**/*/Readme.md"
hostname: https://docs.anycable.io

groups:
  - name: Deployment
    tracking_id: deployment

defaults:
  tags: ["docs"]

pages:
  - "./getting_started.md"
  - source: "./pro.md"
    groups: ["pro"]
  - "./release_notes.md"
  - source: "./troubleshooting.md"
    weight: 3
  - "./upgrade-notes/*.md"
  - "./benchmarks.md"
  - "./misc/*.md"
  - source: "./pro/*.md"
    groups: ["pro"]
  - "./guides/*.md"
  - source: "./deployment/*.md"
    groups: ["deployment"]
